### ISSUE TITLE
Push communication service

### ISSUE THREAD

**Issue by Tatuk** [digiexpress-io/digiexpress-parent#239]
Replace the current fixed push communication service with more configurable service (via theWrench) to  manage the push msg communication to email & suomi.fi delivery channels

Initial implementation minimum requirement is to fulfil of sending email alerts to client subcontractors via email. Suomi.fi channel can be left as it is atm BUT when we start using the new Suomi.fi REST API then also Suomi.fi channel should moved here

https://docs.google.com/presentation/d/1O6aeBeACTPoMAUH-2PltWgt37qafHhDSU1b-vWG4zQ8/edit#slide=id.g22050cddbdd_0_25

- [x] Capture change events from tasks service
- [x] Apply a logic (theWrench) what to do for those events
- [x] Define the content of the msg. like suomi.fi msg (FI only)
- [x] Define the channel (and it's defined structure) to where this msg needs to be pushed
- [x] Store in log the msg it decided to send

**Comment by vahurkrouverk** [comment]
Following issues were detected when tesitng push communication:
1. Flow output is mapped to TaskNotification object, causing following exception:
```
java.lang.IllegalArgumentException: Unrecognized field "enabled" (class io.digiexpress.eveli.client.spi.mq.ImmutableTaskNotification$Json), not marked as ignorable (14 known properties: "taskId", "messageType", "updaterId", "message", "assigneeId", "assigneeEmail", "taskRef", "queue", "taskGroupId", "customerLocale", "customerId", "email", "changeType", "title"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.digiexpress.eveli.client.spi.mq.ImmutableTaskNotification$Json["enabled"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4636) ~[jackson-databind-2.18.2.jar:2.18.2]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4567) ~[jackson-databind-2.18.2.jar:2.18.2]
	at io.resys.thena.jackson.QuarkusJacksonJsonCodec.fromValue(QuarkusJacksonJsonCodec.java:128) ~[thena-db-client-0.y-SNAPSHOT.jar:na]
	at io.vertx.core.json.JsonObject.mapTo(JsonObject.java:423) ~[vertx-core-4.5.11.jar:4.5.11]
	at io.digiexpress.eveli.client.spi.mq.WrenchFlowCommand.runFlow(WrenchFlowCommand.java:92) ~[eveli-integration-queue-0.y-SNAPSHOT.jar:na]
	at io.digiexpress.eveli.client.spi.mq.WrenchFlowCommand.lambda$getQueueMessages$0(WrenchFlowCommand.java:53) ~[eveli-integration-queue-0.y-SNAPSHOT.jar:na]
```
2. When this issue eliminated then following error occurred:
```
java.lang.IllegalArgumentException: Cannot construct instance of `io.digiexpress.eveli.client.spi.mq.ImmutableTaskNotification`, problem: Cannot build TaskNotification, some of required attributes are not set [changeType, customerId, taskRef, messageType]
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4636) ~[jackson-databind-2.18.2.jar:2.18.2]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4567) ~[jackson-databind-2.18.2.jar:2.18.2]
	at io.resys.thena.jackson.QuarkusJacksonJsonCodec.fromValue(QuarkusJacksonJsonCodec.java:128) ~[classes/:na]
	at io.vertx.core.json.JsonObject.mapTo(JsonObject.java:423) ~[vertx-core-4.5.11.jar:4.5.11]
	at io.digiexpress.eveli.client.spi.mq.WrenchFlowCommand.runFlow(WrenchFlowCommand.java:92) ~[classes/:na]
	at io.digiexpress.eveli.client.spi.mq.WrenchFlowCommand.lambda$0(WrenchFlowCommand.java:53) ~[classes/:na]
``` 
3. Communication service failure causes also main operation (task creation/update) failure, but as this service is of secondary importance then it should avoid affecting main operation outcome. Best would to handle communication asynchronously, this also avoids main operation's slowdown due to communication service's execution which involves wrench flow execution. Such errors can occur when wrench workflow takes longer time to complete and timeout occurs.

**Comment by vahurkrouverk** [comment]
issues mentioned under  1 and 3 are fixed with comment https://github.com/digiexpress-io/digiexpress-parent/commit/13e6982a4664313224e42249fd87b15604e406fd

**Comment by vahurkrouverk** [comment]
Issue mentioned #2 required updating of assets with endpoint `/worker/rest/api/assets/wrench/defaultAssets`
Following issues observed after that:
On task saving (occurs occasionally), resulting in remaining on task view and accept button disabled:
```
2025-04-01T12:55:47.432Z ERROR 1 --- [TaskScheduler-5] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void io.digiexpress.eveli.client.spi.mq.PublisherForTaskEvents.publishMessageToQueue(io.digiexpress.eveli.client.spi.mq.MqEventPublisher$MqEvent)
....
java.util.NoSuchElementException: null
	at com.google.common.collect.AbstractIndexedListIterator.next(AbstractIndexedListIterator.java:80) ~[guava-33.3.0-jre.jar:na]
	at io.resys.thena.api.entities.grim.ThenaGrimContainers$GrimMissionContainer.getMission(ThenaGrimContainers.java:58) ~[thena-db-client-0.y-SNAPSHOT.jar:na]
	at io.digiexpress.eveli.client.spi.task.TaskMapper.map(TaskMapper.java:85) ~[eveli-client-0.y-SNAPSHOT.jar:na]
	at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
	at io.digiexpress.eveli.client.spi.task.visitors.TaskDiffVisitor.visitVersion(TaskDiffVisitor.java:75) ~[eveli-client-0.y-SNAPSHOT.jar:na]
	at io.digiexpress.eveli.client.spi.task.visitors.TaskDiffVisitor.lambda$accept$0(TaskDiffVisitor.java:62) ~[eveli-client-0.y-SNAPSHOT.jar:na]
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36) ~[mutiny-2.6.2.jar:2.6.2]
``` 

Exception in flow (when changing status between open and new or priority or adding external comment):
```
io.resys.hdes.client.api.exceptions.ProgramException: Flow switch: 'notification_content' does not match any expressions!
	at io.resys.hdes.client.spi.flow.FlowProgramExecutor.visitSwitchPointer(FlowProgramExecutor.java:482) ~[hdes-client-0.y-SNAPSHOT.jar:na]
	at io.resys.hdes.client.spi.flow.FlowProgramExecutor.visitStep(FlowProgramExecutor.java:168) ~[hdes-client-0.y-SNAPSHOT.jar:na]
	at io.resys.hdes.client.spi.flow.FlowProgramExecutor.visitThenPointer(FlowProgramExecutor.java:436) ~[hdes-client-0.y-SNAPSHOT.jar:na]
	at io.resys.hdes.client.spi.flow.FlowProgramExecutor.visitStep(FlowProgramExecutor.java:167) ~[hdes-client-0.y-SNAPSHOT.jar:na]
	at io.resys.hdes.client.spi.flow.FlowProgramExecutor.visitThenPointer(FlowProgramExecutor.java:436) ~[hdes-client-0.y-SNAPSHOT.jar:na]
	at io.resys.hdes.client.spi.flow.FlowProgramExecutor.visitStep(FlowProgramExecutor.java:167) ~[hdes-client-0.y-SNAPSHOT.jar:na]
	at io.resys.hdes.client.spi.flow.FlowProgramExecutor.run(FlowProgramExecutor.java:85) ~[hdes-client-0.y-SNAPSHOT.jar:na]
	at io.resys.hdes.client.spi.HdesClientExecutorBuilder$2.andGetBody(HdesClientExecutorBuilder.java:123) ~[hdes-client-0.y-SNAPSHOT.jar:na]
	at io.digiexpress.eveli.client.spi.mq.WrenchFlowCommand.runFlow(WrenchFlowCommand.java:76) ~[eveli-integration-queue-0.y-SNAPSHOT.jar:na]
	at io.digiexpress.eveli.client.spi.mq.WrenchFlowCommand.lambda$getQueueMessages$0(WrenchFlowCommand.java:54) ~[eveli-integration-queue-0.y-SNAPSHOT.jar:na]
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36) ~[mutiny-2.6.2.jar:2.6.2]
```

**Comment by Tatuk** [comment]
@olev-mutso We can close this issue but this feature will require documentation how theWrench services are used.
